version: '3.7'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1453
      MYSQL_DATABASE: tkk_proje
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build:
      context: ./  # backend klasörünü build context olarak ayarla
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Backend Docker-Local (Dışarıda-içeride) Port Ayarı
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tkk_proje
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1453
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # Frontend klasöründeki Dockerfile kullanılmalı
    ports:
      - "5173:5173"  # Vite'nin varsayılan portu
    depends_on:
      - app
    environment:
      NODE_ENV: development

volumes:
  mysql-data:


# Çift şeklinde yazan port ayarlarından birincisi local proje portu ikincisi ise docker'ın portu burdan istediğiniz portu ayarlayabilirsiniz.
# Frontend portu için projenin frontend klasörü içindeki docker dosyasından ayarlanabilir.