INSERT INTO `plant` (`id`, `image`, `name`, `yield_per_square_meter`, `category_id`)
VALUES (1, '../../src/assets/Plants/domates.jpg', 'Domates', 8, 1),
       (2, '../../src/assets/Plants/salatalik.jpg', 'Salatalık', 7, 1),
       (3, '../../src/assets/Plants/patates.jpg', 'Patates', 4, 1),
       (4, '../../src/assets/Plants/biber.jpg', 'Biber', 5, 1),
       (5, '../../src/assets/Plants/havuc.jpg', 'Havuç', 6, 1),
       (6, '../../src/assets/Plants/lahana.jpg', 'Lahana', 3, 1),
       (7, '../../src/assets/Plants/patlican.jpg', 'Patlıcan', 6, 1),
       (8, '../../src/assets/Plants/kabak.jpg', 'Kabak', 5, 1),
       (9, '../../src/assets/Plants/marul.jpg', 'Marul', 2, 1),
       (10, '../../src/assets/Plants/ispanak.jpg', 'Ispanak', 3, 1),
       (11, '../../src/assets/Plants/cilek.jpg', 'Çilek', 4, 2),
       (12, '../../src/assets/Plants/armut.jpg', 'Armut', 2, 2),
       (13, '../../src/assets/Plants/elma.jpg', 'Elma', 3, 2),
       (14, '../../src/assets/Plants/portakal.jpg', 'Portakal', 2, 2),
       (15, '../../src/assets/Plants/limon.jpg', 'Limon', 3, 2),
       (16, '../../src/assets/Plants/incir.jpg', 'İncir', 2, 2),
       (17, '../../src/assets/Plants/erik.jpg', 'Erik', 4, 2),
       (18, '../../src/assets/Plants/karpuz.jpg', 'Karpuz', 8, 2),
       (19, '../../src/assets/Plants/kavun.jpg', 'Kavun', 7, 2),
       (20, '../../src/assets/Plants/mandalina.jpg', 'Mandalina', 2, 2),
       (21, '../../src/assets/Plants/buğday.jpg', 'Buğday', 0.8, 3),
       (22, '../../src/assets/Plants/arpa.jpg', 'Arpa', 0.7, 3),
       (23, '../../src/assets/Plants/misir.jpg', 'Mısır', 1.2, 3),
       (24, '../../src/assets/Plants/cavdar.jpg', 'Çavdar', 0.6, 3),
       (25, '../../src/assets/Plants/yulaf.jpg', 'Yulaf', 0.5, 3),
       (26, '../../src/assets/Plants/nohut.jpg', 'Nohut', 1.5, 4),
       (27, '../../src/assets/Plants/mercimek.jpg', 'Mercimek', 1.2, 4),
       (28, '../../src/assets/Plants/fasulye.jpg', 'Fasulye', 1.8, 4),
       (29, '../../src/assets/Plants/bezelye.jpg', 'Bezelye', 2, 4),
       (30, '../../src/assets/Plants/soya.jpg', 'Soya Fasulyesi', 2, 4),
       (31, '../../src/assets/Plants/aycicegi.jpg', 'Ayçiçeği', 1.1, 5),
       (32, '../../src/assets/Plants/kanola.jpg', 'Kanola', 0.9, 5),
       (33, '../../src/assets/Plants/keten.jpg', 'Keten', 0.8, 5),
       (34, '../../src/assets/Plants/aspir.jpg', 'Aspir', 1, 5),
       (35, '../../src/assets/Plants/susam.jpg', 'Susam', 0.7, 5),
       (36, '../../src/assets/Plants/pamuk.jpg', 'Pamuk', 2, 6),
       (37, '../../src/assets/Plants/sugar.jpg', 'Şeker Pancarı', 6, 6),
       (38, '../../src/assets/Plants/tütün.jpg', 'Tütün', 1, 6),
       (39, '../../src/assets/Plants/cay.jpg', 'Çay', 4, 6),
       (40, '../../src/assets/Plants/kenevir.jpg', 'Kenevir', 2, 6),
       (41, '../../src/assets/Plants/nane.jpg', 'Nane', 2, 7),
       (42, '../../src/assets/Plants/adaçayı.jpg', 'Adaçayı', 1.5, 7),
       (43, '../../src/assets/Plants/kekik.jpg', 'Kekik', 1.2, 7),
       (44, '../../src/assets/Plants/çörekotu.jpg', 'Çörek Otu', 0.5, 7),
       (45, '../../src/assets/Plants/rezene.jpg', 'Rezene', 1, 7),
       (46, '../../src/assets/Plants/lavanta.jpg', 'Lavanta', 0.8, 8),
       (47, '../../src/assets/Plants/melisa.jpg', 'Melisa', 1, 8),
       (48, '../../src/assets/Plants/papatya.jpg', 'Papatya', 0.6, 8),
       (49, '../../src/assets/Plants/okaliptus.jpg', 'Okaliptus', 3, 8),
       (50, '../../src/assets/Plants/biberiye.jpg', 'Biberiye', 1.3, 8);